# Generated by targets: do not edit by hand
library(targets)

# Source all R files
lapply(list.files("R", full.names = TRUE, pattern = "\\.R$"), source)

# Pipeline configuration
list(
  # Data ingestion targets
  tar_target(tcga_data, {
    fetch_tcga_data(project = config$project,
                    data_types = c("expression", "clinical", "mutation"))
  }),

  tar_target(ppi_data, {
    genes <- rownames(SummarizedExperiment::assay(tcga_data$expression))[1:500]
    fetch_string_ppi(genes)
  }),

  # Preprocessing targets
  tar_target(expression_clean, {
    expr <- SummarizedExperiment::assay(tcga_data$expression)
    expr <- filter_low_expression(expr)
    normalize_counts(expr, method = "vst")
  }),

  tar_target(clinical_clean, {
    harmonize_clinical(tcga_data$clinical)
  }),

  # Analysis targets
  tar_target(de_results, {
    col_data <- data.frame(
      condition = factor(ifelse(grepl("Tumor", colnames(expression_clean)),
                                "tumor", "normal")),
      row.names = colnames(expression_clean)
    )
    consensus_de(expression_clean, col_data)
  }),

  tar_target(survival_results, {
    calculate_hazard_ratios(
      expression_clean,
      time = clinical_clean$time,
      status = clinical_clean$status,
      genes = head(de_results$gene, 100)
    )
  }),

  tar_target(network_results, {
    g <- build_ppi_network(ppi_data)
    list(
      network = g,
      centrality = calculate_network_centrality(g),
      modules = detect_network_modules(g)
    )
  }),

  tar_target(crispr_scores, {
    depmap <- fetch_depmap_crispr()
    if (!is.null(depmap)) {
      data.frame(
        gene = colnames(depmap),
        dependency_score = colMeans(depmap, na.rm = TRUE),
        stringsAsFactors = FALSE
      )
    } else {
      NULL
    }
  }),

  # Target scoring
  tar_target(scored_targets, {
    composite_target_score(
      de_results = de_results,
      survival_hr = survival_results,
      centrality = network_results$centrality,
      crispr_scores = crispr_scores
    )
  }),

  tar_target(ranked_targets, {
    rank_targets(scored_targets, top_n = 50)
  }),

  # Agentic assessment
  tar_target(gap_analysis, {
    agent <- GapDetectionAgent$new()
    results <- list(
      de = de_results,
      survival = survival_results,
      network = network_results,
      scoring = scored_targets
    )
    data <- list(
      expression = expression_clean,
      clinical = clinical_clean,
      ppi = ppi_data
    )
    agent$detect(results, data)
    agent$summary()
  }),

  # Evaluation
  tar_target(evaluation, {
    gs <- build_reference_panel()
    eval_agent <- EvaluationAgent$new()
    eval_agent$evaluate(ranked_targets, gs)
    eval_agent$state$metrics
  }),

  # Final output
  tar_target(final_report, {
    gs <- build_reference_panel()
    generate_evaluation_report(
      ranked_targets,
      gs,
      output_file = "results/evaluation_report.md"
    )
  })
)
